In [2]:
import numpy as np

### Write a NumPy program to test whether none of the elements of a given array is zero.

In [9]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,0,3,4])
arr3 = np.array([0,0,0,0])

In [11]:
def is_any_zeros(arr):
    if np.all(arr) == True:
        print("no zeros in the array")
    else:
        print("there is zeros in the array")

In [13]:
is_any_zeros(arr1)
is_any_zeros(arr2)
is_any_zeros(arr3)

no zeros in the array
there is zeros in the array
there is zeros in the array


### Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [38]:
def _10zeros_10ones_10fives():
    a = np.zeros(10)
    b = np.ones(10)
    c = np.ones(10) * 5
    d = np.hstack((a,b,c))
    return d

In [40]:
_10zeros_10ones_10fives()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Write a NumPy program to create an array of the integers from 30 to70

In [43]:
def arr_30_to_70():
    a = np.arange(30,71)
    return a

In [45]:
arr_30_to_70()

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### Write a NumPy program to create a 3x3 identity matrix

In [48]:
def _3x3_identity_matrix():
    a = np.identity(3)
    return a

In [52]:
_3x3_identity_matrix()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Write a NumPy program to generate a random number between 0 and 1

In [55]:
def random_number_between_0_and_1():
    a = np.random.rand(1)
    return a

In [63]:
random_number_between_0_and_1()

array([0.97285707])

### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [68]:
def _15random_number_standard_normal_distribution():
    a = np.random.randn(15)
    return a

In [70]:
_15random_number_standard_normal_distribution()

array([-1.1740274 , -0.93239525,  0.21821172, -0.54329653,  0.44954327,
       -0.04114661, -0.87538557,  0.92061444, -0.32014653, -1.2326642 ,
       -0.58767673,  0.97959822,  0.45435681,  0.77674056,  0.05448449])

### Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [73]:
def from_15_to_55():
    a = np.arange(16,55)
    return a

In [75]:
from_15_to_55()

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

### Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [104]:
def from_0_to_10():
    a = np.arange(0,10,(2))
    return a

In [106]:
from_0_to_10()

array([0, 2, 4, 6, 8])

### Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [150]:
#def borders1_inside0():
a = np.ones((10,10))
a[1:-1,1:-1] = 0

In [152]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [155]:
def zero_diag():
    diag = np.array([1,2,3,4,5])
    arr = np.diag(diag)
    return arr

In [157]:
zero_diag()

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [36]:
def diagonal():
    arr = np.ones((4,4))
    
    for i in range(2):
        arr[1::2,1::2] = 0
        arr[:3:2,:3:2] = 0
    return arr

In [38]:
diagonal()

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

### Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select.

In [68]:
def forty_random():
    arr = np.random.random(40)
    return arr

In [70]:
forty_random()

array([0.48479809, 0.78435618, 0.86896312, 0.63319229, 0.69481484,
       0.3496814 , 0.85439748, 0.51008491, 0.84321096, 0.53687677,
       0.38041104, 0.53784992, 0.62442625, 0.15665866, 0.18077394,
       0.678847  , 0.59042861, 0.52041511, 0.82570165, 0.18960223,
       0.55691273, 0.88666105, 0.17478702, 0.43664138, 0.98812559,
       0.23742357, 0.47711769, 0.80976593, 0.04360707, 0.84029235,
       0.50260215, 0.72167379, 0.56446744, 0.74605686, 0.27716088,
       0.64474206, 0.46448155, 0.74485144, 0.83834667, 0.97737291])

### Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [75]:
def less_more(arr,num):
    numbers = list(filter(lambda x : x > num or x < num, arr))
    return numbers
    
    

In [82]:
arr1 = np.arange(5)
number = 3
less_more(arr1,number)

[0, 1, 2, 4]